image: $CI_REGISTRY/ricardomartincoski_opensource/sblkh/sblkh:20230409.2219

variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  before_script:
    # avoid https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29022
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
    # avoid https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29022 for pkg-stats
    - git config --global --add safe.directory ${CI_PROJECT_DIR}/buildroot
    # fix timestamps change (that triggers unneeded rebuild) when extracting artifacts created using exclude rules
    - touch -t $(date +%Y%m%d%H%M.%S) -c output/build/*/.stamp_*
    # improve troubleshooting for passing artifacts from one job to another
    - for dir in
        .
        download
        output/build
        output/images
        output/needed-images
        ; do if [ -d $dir ]; then echo $dir ; ls -la $dir ; fi; done

cache: &global_cache
  key: single-cache
  paths:
    - .ccache/
    - download/
  policy: pull-push

stages:
  - pre-build
  - static-analysis
  - build
  - post-build
  - runtime-test

check-package:
  stage: static-analysis
  cache: []
  script:
    - make check-package

check-flake8:
  stage: static-analysis
  cache: []
  script:
    - make check-flake8

checkpatch.pl:
  stage: static-analysis
  cache:
    <<: *global_cache
    policy: pull
  needs:
    - job: source
  script:
    - make checkpatch.pl

.intermediary_build:
  artifacts:
    when: always
    expire_in: 4 hours
    paths:
      - .stamp_*
      # do not use output/build/**/.stamp_* because the folder would be created with root ownership
      - output/
    exclude:
      # avoid ERROR: Uploading artifacts as "archive" to coordinator... 413 Payload Too Large
      # but allow target-finalize to install modules by keeping:
      # - build/linux-*/include/
      # - build/linux-*/scripts/
      # - build/linux-*/Makefile
      - output/build/[^l]*/**/[^.]*
      - output/build/l*/[^is]**/[^.M]*
      - output/build/l*/s[^c]**/[^.]*

configure:
  stage: pre-build
  extends: .intermediary_build
  script:
    - make configure

source:
  stage: pre-build
  extends: .intermediary_build
  needs:
    - job: configure
  script:
    - make source

toolchain:
  stage: build
  extends: .intermediary_build
  needs:
    - job: source
  script:
    - make toolchain

uboot:
  stage: build
  extends: .intermediary_build
  needs:
    - job: toolchain
  script:
    - make uboot

arm-trusted-firmware:
  stage: build
  extends: .intermediary_build
  needs:
    - job: uboot
  script:
    - make arm-trusted-firmware

grub2:
  stage: build
  extends: .intermediary_build
  needs:
    - job: arm-trusted-firmware
  script:
    - make grub2

linux-depends:
  stage: build
  extends: .intermediary_build
  needs:
    - job: grub2
  script:
    - make linux-depends

linux:
  stage: build
  extends: .intermediary_build
  needs:
    - job: linux-depends
  script:
    - make linux

images:
  stage: build
  extends: .intermediary_build
  needs:
    - job: linux
  script:
    - make images

needed-images:
  stage: post-build
  cache: []
  needs:
    - job: images
  script:
    - make needed-images
  artifacts:
    when: always
    paths:
      - .stamp_*
      - output/br.log
      - output/needed-images/

legal-info:
  stage: post-build
  needs:
    - job: configure
  script:
    - make legal-info
  artifacts:
    when: always
    paths:
      - output/br.log
      - output/legal-info/

graphs:
  stage: post-build
  cache: []
  needs:
    - job: images
  script:
    - make graphs
  artifacts:
    when: always
    paths:
      - output/br.log
      - output/graphs/

pkg-stats:
  stage: post-build
  needs:
    - job: configure
  script:
    - make pkg-stats
  artifacts:
    when: always
    paths:
      - output/br.log
      - output/pkg-stats.*

test:
  stage: runtime-test
  cache: []
  needs:
    - job: needed-images
  script:
    - make test
  artifacts:
    when: always
    paths:
      - .stamp_*
      - output/br.log
      - output/needed-images/
      - output/tests/
